# Generated by Django 5.2.5 on 2025-08-17 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_alter_lesson_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="course",
        ),
        migrations.AddField(
            model_name="course",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите урок",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="materials.lesson",
                verbose_name="Урок",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(default=""),
        ),
    ]
